### PR TITLE
Include SPDX line in source code files

### PR DESCRIPTION
**Pull request by marcusburghardt**
This is in alignment with [Project Style Guide](https://github.com/complytime/complytime/blob/main/docs/STYLE_GUIDE.md#licensing-and-file-headers).

### CODE REVIEW

**Review by jpower432 — CHANGES_REQUESTED** [review]
@marcusburghardt Can you please add a newline after each SPDX comment? Comments immediately above the package declaration are usually for Go Doc comments.

**Comment by marcusburghardt** [comment]
> @marcusburghardt Can you please add a newline after each SPDX comment? Comments immediately above the package declaration are usually for Go Doc comments.

To be honest I initially left a newline there but when checking some other go projects and best practices I removed them. I probably interpreted it wrong. : )) Thanks for pointing this. I will fix now.

**Review by jpower432 — DISMISSED** [review]
LGTM

**Comment by qduanmu** [comment]
@marcusburghardt should there be a license header in source files under `version` dir?

**Comment by marcusburghardt** [comment]
> @marcusburghardt should there be a license header in source files under `version` dir?

Good catch. Updated. Thanks

**Review by qduanmu — APPROVED** [review]

**Review by jpower432 — APPROVED** [review]
LGTM

**Review by vojtapolasek — APPROVED** [review]
LGTM

**Pull request merged**
